name: Build and Test monitored
true:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
jobs:
  build-and-test-monitored:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.17.0
    - uses: listendev/action@v0.11
      with:
        ci: only
        jwt: ${{ secrets.LSTN }}
    - name: Install dependencies
      run: npm install
      working-directory: customer-support-agent
    - name: Build project
      run: npm run build
      working-directory: customer-support-agent
    - name: Run tests
      run: npm test
      working-directory: customer-support-agent
